project_id = "bywurhidxhmgpxmxlpzf"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.parse-book-structure]
verify_jwt = false

[functions.proxy-api-test]
verify_jwt = false

[functions.dotpoint-api-test]
verify_jwt = false

[functions.segment-scene]
verify_jwt = false

[functions.openrouter-proxy]
verify_jwt = false

[functions.yandex-tts]
verify_jwt = false

[functions.profile-characters]
verify_jwt = false

[functions.elevenlabs-sfx]
verify_jwt = false

[functions.elevenlabs-music]
verify_jwt = false
